# See Elttob's original mkdocs.yml file here: https://github.com/Elttob/Fusion/blob/main/mkdocs.yml

site_name: ro.py
site_url: https://ro.py.jmk.gg/
repo_name: rbx-libdev/ro.py
repo_url: https://github.com/rbx-libdev/ro.py
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: black
    accent: blue

extra_css:
  - assets/theme.css

plugins:
  - search
  - mermaid2:
      arguments:
        theme: dark
  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
          - import sys
          - sys.path.append("docs")
          selection:
            new_path_syntax: yes
          rendering:
            show_if_no_docstring: yes
            show_signature_annotations: yes
            show_root_heading: yes

markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.highlight:
      guess_lang: false
  - toc:
      permalink: true