name: MkDocs Deploy

on:
  workflow_dispatch:
    inputs:
      name:
        description: "MkDocs Deploy"
  push:
    branches:
      - "main"
    paths:
      - "roblox/**"
      - "docs/**"
      - ".github/workflows/**"
      - "mkdocs.yml"

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.7"
      
      - name: Install dependencies
        run: |
          pip install git+https://github.com/squidfunk/mkdocs-material.git@8.0.0b2
          pip install mkdocstrings httpx mkdocs-literate-nav mkdocs-gen-files mike
      
      - name: Build docs
        run: |
          mkdocs build
      
      - name: Configure Git author
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      
      - name: Deploy docs
        run: |
          mike deploy dev
