name: MkDocs Deploy

on:
  workflow_dispatch:
    inputs:
      name:
        description: "MkDocs Deploy"
  push:
    branches:
      - "main"
    paths:
      - "roblox/**"
      - "docs/**"
      - ".github/workflows/**"
      - "mkdocs.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install git+https://github.com/squidfunk/mkdocs-material.git@8.0.0b2
      - run: pip install mkdocstrings httpx mkdocs-literate-nav mkdocs-gen-files mkdocs-mermaid2-plugin
      - run: mkdocs gh-deploy --force
